-- Create order_requests table if not exists (Separate from orders table)
CREATE TABLE IF NOT EXISTS public.order_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    display_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    total_amount NUMERIC,
    delivery_cost NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Pendiente',
    items JSONB,
    customer_info JSONB,
    product_ids TEXT[]
);

-- Ensure RLS is enabled
ALTER TABLE public.order_requests ENABLE ROW LEVEL SECURITY;

-- Allow public insert (for initial requests) specific if no auth
CREATE POLICY "Public can insert order_requests" ON public.order_requests FOR
INSERT
WITH
    CHECK (true);

-- Allow admins/all to read (change as needed)
CREATE POLICY "Public can view order_requests" ON public.order_requests FOR
SELECT USING (true);

-- Allow update/delete (for confirm/deny)
CREATE POLICY "Public can update order_requests" ON public.order_requests FOR
UPDATE USING (true);

CREATE POLICY "Public can delete order_requests" ON public.order_requests FOR DELETE USING (true);

-- Also Ensure 'orders' table is ready for migration from requests
-- We assume 'orders' table already exists.